Repository EQUIPO-11-CONSTR-APLIC-MOVILES/Team-11-Kotlin, pull requests merged in 2024-12, with the labels that each got.

#186 Feature/user detail screen#181
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/restau/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/example/restau/data/repository/UsersRepositoryImpl.kt
  app/src/main/java/com/example/restau/di/AppModule.kt
  app/src/main/java/com/example/restau/domain/repository/AuthRepository.kt
  app/src/main/java/com/example/restau/domain/repository/UsersRepository.kt
  app/src/main/java/com/example/restau/domain/usecases/authUseCases/AuthUseCases.kt
  app/src/main/java/com/example/restau/domain/usecases/authUseCases/ExecuteLogOut.kt
  app/src/main/java/com/example/restau/domain/usecases/userUseCases/UpdateReviewsAuthorInfo.kt
  app/src/main/java/com/example/restau/domain/usecases/userUseCases/UpdateUserInfo.kt
  app/src/main/java/com/example/restau/domain/usecases/userUseCases/UploadUserImage.kt
  app/src/main/java/com/example/restau/domain/usecases/userUseCases/UserUseCases.kt
  app/src/main/java/com/example/restau/presentation/home/HomeEvent.kt
  app/src/main/java/com/example/restau/presentation/home/HomeScreen.kt
  app/src/main/java/com/example/restau/presentation/home/HomeViewModel.kt
  app/src/main/java/com/example/restau/presentation/liked/LikedEvent.kt
  app/src/main/java/com/example/restau/presentation/liked/LikedScreen.kt
  app/src/main/java/com/example/restau/presentation/liked/LikedViewModel.kt
  app/src/main/java/com/example/restau/presentation/navigation/NavGraph.kt
  app/src/main/java/com/example/restau/presentation/navigation/Route.kt
  app/src/main/java/com/example/restau/presentation/search/SearchEvent.kt
  app/src/main/java/com/example/restau/presentation/search/SearchScreen.kt
  app/src/main/java/com/example/restau/presentation/search/SearchViewModel.kt
  app/src/main/java/com/example/restau/presentation/userdetail/UserDetailEvent.kt
  app/src/main/java/com/example/restau/presentation/userdetail/UserDetailScreen.kt
  app/src/main/java/com/example/restau/presentation/userdetail/UserDetailState.kt
  app/src/main/java/com/example/restau/presentation/userdetail/UserDetailViewModel.kt
Labels: enhancement

#192 Shared Preferences user information
  app/src/main/java/com/example/restau/data/repository/UsersRepositoryImpl.kt
  app/src/main/java/com/example/restau/di/AppModule.kt
  app/src/main/java/com/example/restau/presentation/menuItems/MenuItemsEvent.kt
  app/src/main/java/com/example/restau/presentation/menuItems/MenuItemsScreen.kt
  app/src/main/java/com/example/restau/presentation/menuItems/MenuItemsViewModel.kt
  app/src/main/java/com/example/restau/presentation/userdetail/UserDetailScreen.kt
Labels: enhancement

#194 Micro optimization index
  app/src/main/java/com/example/restau/presentation/search/SearchScreen.kt
Labels: enhancement

#196 Show Distance BQ done
  app/src/main/java/com/example/restau/presentation/restaurant/RestaurantScreen.kt
  app/src/main/java/com/example/restau/presentation/restaurant/RestaurantState.kt
  app/src/main/java/com/example/restau/presentation/restaurant/RestaurantViewModel.kt
Labels: enhancement

#198 Fix
  app/src/main/java/com/example/restau/presentation/userdetail/UserDetailScreen.kt
Labels: fix

#200 Fixing likes
  app/src/main/java/com/example/restau/data/repository/UsersRepositoryImpl.kt
Labels: fix

#202 Including error icon on menu item images for when image network reque…
  app/src/main/java/com/example/restau/presentation/menuItems/components/MenuItemCard.kt
Labels: fix

#206 done fix
  app/src/main/java/com/example/restau/presentation/restaurant/RestaurantScreen.kt
Labels: fix

#207 Fix preferences
  .idea/gradle.xml
  app/src/main/java/com/example/restau/data/repository/UsersRepositoryImpl.kt
Labels: bug

#208 Sprint 4
  .idea/gradle.xml
  app/src/main/java/com/example/restau/data/repository/UsersRepositoryImpl.kt
  app/src/main/java/com/example/restau/presentation/restaurant/RestaurantScreen.kt
Labels: enhancement

#210 Fix
  app/src/main/java/com/example/restau/presentation/userdetail/UserDetailScreen.kt
Labels: bug
