Repository EQUIPO-11-CONSTR-APLIC-MOVILES/Team-11-Kotlin, pull requests merged in 2024-09, with the labels that each got.

#10 Project creation. Empty Jetpack Compose Activity.
  .gitignore
  app/.gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/restau/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/restau/MainActivity.kt
  app/src/main/java/com/example/restau/ui/theme/Color.kt
  app/src/main/java/com/example/restau/ui/theme/Theme.kt
  app/src/main/java/com/example/restau/ui/theme/Type.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/example/restau/ExampleUnitTest.kt
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: enhancement

#11 Issue#8 include initial dependencies
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/other.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  build.gradle.kts
  gradle/libs.versions.toml
  local.defaults.properties
Labels: enhancement

#12 Project structure and general elements created and configured
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/restau/MainActivity.kt
  app/src/main/java/com/example/restau/RestaUApplication.kt
  app/src/main/java/com/example/restau/di/AppModule.kt
  app/src/main/java/com/example/restau/ui/theme/Color.kt
  app/src/main/java/com/example/restau/ui/theme/Shape.kt
  app/src/main/java/com/example/restau/ui/theme/Theme.kt
  app/src/main/java/com/example/restau/ui/theme/Type.kt
  app/src/main/java/com/example/restau/utils/Constants.kt
  app/src/main/res/font/poppins_black.ttf
  app/src/main/res/font/poppins_bold.ttf
  app/src/main/res/font/poppins_extrabold.ttf
  app/src/main/res/font/poppins_extralight.ttf
  app/src/main/res/font/poppins_light.ttf
  app/src/main/res/font/poppins_medium.ttf
  app/src/main/res/font/poppins_regular.ttf
  app/src/main/res/font/poppins_semibold.ttf
  app/src/main/res/font/poppins_thin.ttf
  app/src/main/res/values/dimens.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: enhancement

#27 Issue#13 splash screen navigation
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/restau/MainActivity.kt
  app/src/main/java/com/example/restau/presentation/home/HomeScreen.kt
  app/src/main/java/com/example/restau/presentation/liked/LikedScreen.kt
  app/src/main/java/com/example/restau/presentation/map/MapScreen.kt
  app/src/main/java/com/example/restau/presentation/navigation/NavGraph.kt
  app/src/main/java/com/example/restau/presentation/navigation/Route.kt
  app/src/main/java/com/example/restau/presentation/navigator/NavigatorEvent.kt
  app/src/main/java/com/example/restau/presentation/navigator/NavigatorScreen.kt
  app/src/main/java/com/example/restau/presentation/navigator/NavigatorViewModel.kt
  app/src/main/java/com/example/restau/presentation/navigator/components/NavBar.kt
  app/src/main/java/com/example/restau/presentation/random/RandomScreen.kt
  app/src/main/java/com/example/restau/presentation/search/SearchScreen.kt
  app/src/main/java/com/example/restau/presentation/splashscreen/SplashScreen.kt
  app/src/main/res/drawable/error.xml
  app/src/main/res/drawable/like.xml
  app/src/main/res/drawable/map.xml
  app/src/main/res/drawable/random.xml
  app/src/main/res/drawable/restau.png
  app/src/main/res/drawable/restaurant.xml
  app/src/main/res/drawable/search.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#28 Configuration of firestore in dependency injection.
  app/src/main/java/com/example/restau/data/repository/RecentsRepositoryImpl.kt
  app/src/main/java/com/example/restau/data/repository/RestaurantsRepositoryImpl.kt
  app/src/main/java/com/example/restau/di/AppModule.kt
  app/src/main/java/com/example/restau/domain/model/Restaurant.kt
  app/src/main/java/com/example/restau/domain/repository/RecentsRepository.kt
  app/src/main/java/com/example/restau/domain/repository/RestaurantsRepository.kt
  app/src/main/java/com/example/restau/domain/usecases/GetRecents.kt
  app/src/main/java/com/example/restau/domain/usecases/GetRestaurants.kt
  app/src/main/java/com/example/restau/domain/usecases/RecentsUseCases.kt
  app/src/main/java/com/example/restau/domain/usecases/RestaurantUseCases.kt
  app/src/main/java/com/example/restau/domain/usecases/SaveRecents.kt
  app/src/main/java/com/example/restau/utils/Constants.kt
Labels: enhancement

#32 Fixing the model schedule attribute
  app/src/main/java/com/example/restau/domain/model/Restaurant.kt
Labels: bug

#41 Issue#19 main screen
  .idea/deploymentTargetSelector.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/example/restau/data/repository/RestaurantsRepositoryImpl.kt
  app/src/main/java/com/example/restau/di/AppModule.kt
  app/src/main/java/com/example/restau/domain/repository/RestaurantsRepository.kt
  app/src/main/java/com/example/restau/domain/usecases/GetIsNewRestaurantArray.kt
  app/src/main/java/com/example/restau/domain/usecases/GetOpenRestaurants.kt
  app/src/main/java/com/example/restau/domain/usecases/GetRestaurants.kt
  app/src/main/java/com/example/restau/domain/usecases/RestaurantUseCases.kt
  app/src/main/java/com/example/restau/presentation/common/DynamicTopBar.kt
  app/src/main/java/com/example/restau/presentation/common/RestaurantCard.kt
  app/src/main/java/com/example/restau/presentation/common/TopBarAction.kt
  app/src/main/java/com/example/restau/presentation/home/HomeEvent.kt
  app/src/main/java/com/example/restau/presentation/home/HomeScreen.kt
  app/src/main/java/com/example/restau/presentation/home/HomeState.kt
  app/src/main/java/com/example/restau/presentation/home/HomeViewModel.kt
  app/src/main/java/com/example/restau/presentation/navigation/Route.kt
  app/src/main/java/com/example/restau/presentation/navigator/NavigatorScreen.kt
  app/src/main/res/drawable/clock.xml
  app/src/main/res/drawable/filled_like.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/kid_star.xml
  app/src/main/res/drawable/map_filled.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: enhancement

#60 Feature/map screen #17
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/restau/data/repository/ImageRepositoryImpl.kt
  app/src/main/java/com/example/restau/data/repository/LocationRepositoryImpl.kt
  app/src/main/java/com/example/restau/di/AppModule.kt
  app/src/main/java/com/example/restau/domain/repository/ImageRepository.kt
  app/src/main/java/com/example/restau/domain/repository/LocationRepository.kt
  app/src/main/java/com/example/restau/domain/usecases/DownloadImages.kt
  app/src/main/java/com/example/restau/domain/usecases/DownloadSingleImage.kt
  app/src/main/java/com/example/restau/domain/usecases/GetLocation.kt
  app/src/main/java/com/example/restau/domain/usecases/GetRestaurantsInRadius.kt
  app/src/main/java/com/example/restau/domain/usecases/ImageDownloadUseCases.kt
  app/src/main/java/com/example/restau/domain/usecases/LocationUseCases.kt
  app/src/main/java/com/example/restau/domain/usecases/RestaurantUseCases.kt
  app/src/main/java/com/example/restau/presentation/common/LoadingCircle.kt
  app/src/main/java/com/example/restau/presentation/common/StarRating.kt
  app/src/main/java/com/example/restau/presentation/home/HomeScreen.kt
  app/src/main/java/com/example/restau/presentation/map/MapEvent.kt
  app/src/main/java/com/example/restau/presentation/map/MapScreen.kt
  app/src/main/java/com/example/restau/presentation/map/MapState.kt
  app/src/main/java/com/example/restau/presentation/map/MapViewModel.kt
  app/src/main/java/com/example/restau/presentation/map/components/CardMarker.kt
  app/src/main/java/com/example/restau/presentation/map/components/NoPermissionsSign.kt
  app/src/main/java/com/example/restau/presentation/map/components/SliderCard.kt
  app/src/main/java/com/example/restau/ui/theme/Color.kt
  app/src/main/java/com/example/restau/utils/HasLocationPermissionExtension.kt
  app/src/main/res/drawable/empty_star.xml
  app/src/main/res/drawable/half_star.xml
  app/src/main/res/drawable/no_permissions.xml
  app/src/main/res/drawable/star.xml
  gradle/libs.versions.toml
Labels: enhancement

#59 Search Screen Implementation
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/restau/di/AppModule.kt
  app/src/main/java/com/example/restau/domain/usecases/GetFilterRestaurantsByNameAndCategories.kt
  app/src/main/java/com/example/restau/domain/usecases/RestaurantUseCases.kt
  app/src/main/java/com/example/restau/presentation/common/RestaurantCard.kt
  app/src/main/java/com/example/restau/presentation/home/HomeScreen.kt
  app/src/main/java/com/example/restau/presentation/search/SearchEvent.kt
  app/src/main/java/com/example/restau/presentation/search/SearchScreen.kt
  app/src/main/java/com/example/restau/presentation/search/SearchState.kt
  app/src/main/java/com/example/restau/presentation/search/SearchViewModel.kt
  app/src/main/res/drawable/cleartext.xml
  app/src/main/res/drawable/microphone.xml
  app/src/main/res/values/SearchScreenUI.xml
Labels: enhancement

#58 Feature/Issue#18 Complete Functional Sign-In Screen Implementation
  .gitignore
  .idea/other.xml
  app/build.gradle.kts
  app/src/main/java/com/example/restau/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/example/restau/di/AppModule.kt
  app/src/main/java/com/example/restau/domain/model/User.kt
  app/src/main/java/com/example/restau/domain/repository/AuthRepository.kt
  app/src/main/java/com/example/restau/domain/usecases/AuthUseCases.kt
  app/src/main/java/com/example/restau/domain/usecases/ExecuteSignIn.kt
  app/src/main/java/com/example/restau/domain/usecases/GetCurrentUser.kt
  app/src/main/java/com/example/restau/presentation/common/TopBarAction.kt
  app/src/main/java/com/example/restau/presentation/navigation/NavGraph.kt
  app/src/main/java/com/example/restau/presentation/navigation/Route.kt
  app/src/main/java/com/example/restau/presentation/navigator/NavigatorEvent.kt
  app/src/main/java/com/example/restau/presentation/navigator/NavigatorScreen.kt
  app/src/main/java/com/example/restau/presentation/navigator/NavigatorViewModel.kt
  app/src/main/java/com/example/restau/presentation/signin/SignInEvent.kt
  app/src/main/java/com/example/restau/presentation/signin/SignInScreen.kt
  app/src/main/java/com/example/restau/presentation/signin/SignInState.kt
  app/src/main/java/com/example/restau/presentation/signin/SignInViewModel.kt
  app/src/main/res/drawable/google_icon.xml
  app/src/main/res/drawable/restau_1_.png
  gradle/libs.versions.toml
Labels: enhancement

#65 Import merge error fixed.
  app/src/main/java/com/example/restau/di/AppModule.kt
Labels: fix

#66 Sign In Glitch Fixed
  app/src/main/java/com/example/restau/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/example/restau/domain/repository/AuthRepository.kt
  app/src/main/java/com/example/restau/domain/usecases/GetCurrentUser.kt
  app/src/main/java/com/example/restau/presentation/navigation/NavGraph.kt
  app/src/main/java/com/example/restau/presentation/navigator/NavigatorScreen.kt
  app/src/main/java/com/example/restau/presentation/navigator/NavigatorViewModel.kt
  app/src/main/java/com/example/restau/presentation/signin/SignInEvent.kt
  app/src/main/java/com/example/restau/presentation/signin/SignInScreen.kt
  app/src/main/java/com/example/restau/presentation/signin/SignInViewModel.kt
Labels: fix

#67 Homescreen user-related functionalities
  .idea/deploymentTargetSelector.xml
  .idea/other.xml
  app/src/main/java/com/example/restau/data/repository/UsersRepositoryImpl.kt
  app/src/main/java/com/example/restau/di/AppModule.kt
  app/src/main/java/com/example/restau/domain/model/User.kt
  app/src/main/java/com/example/restau/domain/repository/UsersRepository.kt
  app/src/main/java/com/example/restau/domain/usecases/GetRestaurantsLiked.kt
  app/src/main/java/com/example/restau/domain/usecases/GetUserObject.kt
  app/src/main/java/com/example/restau/domain/usecases/RestaurantUseCases.kt
  app/src/main/java/com/example/restau/domain/usecases/SendLike.kt
  app/src/main/java/com/example/restau/domain/usecases/UserUseCases.kt
  app/src/main/java/com/example/restau/presentation/home/HomeEvent.kt
  app/src/main/java/com/example/restau/presentation/home/HomeScreen.kt
  app/src/main/java/com/example/restau/presentation/home/HomeViewModel.kt
Labels: enhancement

#68 feature/special-pin-#25
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/restau/di/AppModule.kt
  app/src/main/java/com/example/restau/domain/usecases/HasLikedCategoriesArray.kt
  app/src/main/java/com/example/restau/domain/usecases/RestaurantUseCases.kt
  app/src/main/java/com/example/restau/presentation/home/HomeViewModel.kt
  app/src/main/java/com/example/restau/presentation/map/MapEvent.kt
  app/src/main/java/com/example/restau/presentation/map/MapScreen.kt
  app/src/main/java/com/example/restau/presentation/map/MapState.kt
  app/src/main/java/com/example/restau/presentation/map/MapViewModel.kt
  app/src/main/java/com/example/restau/presentation/map/components/CardMarker.kt
  app/src/main/res/drawable/specialpin.png
Labels: enhancement

#70 Feature/screen time #69
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/restau/data/repository/ScreenTimeEventsRepositoryImpl.kt
  app/src/main/java/com/example/restau/di/AppModule.kt
  app/src/main/java/com/example/restau/domain/model/ScreenTimeEvent.kt
  app/src/main/java/com/example/restau/domain/repository/ScreenTimeEventsRepository.kt
  app/src/main/java/com/example/restau/domain/usecases/AnalyticsUseCases.kt
  app/src/main/java/com/example/restau/domain/usecases/SendScreenTimeEvent.kt
  app/src/main/java/com/example/restau/presentation/home/HomeEvent.kt
  app/src/main/java/com/example/restau/presentation/home/HomeScreen.kt
  app/src/main/java/com/example/restau/presentation/home/HomeViewModel.kt
  app/src/main/java/com/example/restau/presentation/liked/LikedEvent.kt
  app/src/main/java/com/example/restau/presentation/liked/LikedScreen.kt
  app/src/main/java/com/example/restau/presentation/liked/LikedViewModel.kt
  app/src/main/java/com/example/restau/presentation/map/MapEvent.kt
  app/src/main/java/com/example/restau/presentation/map/MapScreen.kt
  app/src/main/java/com/example/restau/presentation/map/MapViewModel.kt
  app/src/main/java/com/example/restau/presentation/search/SearchEvent.kt
  app/src/main/java/com/example/restau/presentation/search/SearchScreen.kt
  app/src/main/java/com/example/restau/presentation/search/SearchViewModel.kt
  gradle/libs.versions.toml
Labels: enhancement

#71 Voice recognition implementation
  app/src/main/java/com/example/restau/presentation/search/SearchEvent.kt
  app/src/main/java/com/example/restau/presentation/search/SearchScreen.kt
  app/src/main/java/com/example/restau/presentation/search/SearchViewModel.kt
Labels: enhancement

#75 Added Events to update state
  app/src/main/java/com/example/restau/presentation/signin/SignInEvent.kt
  app/src/main/java/com/example/restau/presentation/signin/SignInScreen.kt
  app/src/main/java/com/example/restau/presentation/signin/SignInViewModel.kt
Labels: fix
