Repository EQUIPO-11-CONSTR-APLIC-MOVILES/Team-11-Kotlin, pull requests merged in 2024-11, with the labels that each got.

#153 Eventual Connectivity management review creation / search screen
  app/src/main/java/com/example/restau/presentation/reviewcreation/ReviewCreationScreen.kt
  app/src/main/java/com/example/restau/presentation/reviewcreation/ReviewCreationViewModel.kt
  app/src/main/java/com/example/restau/presentation/search/SearchEvent.kt
  app/src/main/java/com/example/restau/presentation/search/SearchScreen.kt
  app/src/main/java/com/example/restau/presentation/search/SearchViewModel.kt
Labels: enhancement

#155 Eventual Connectivity RandomScreen
  app/src/main/java/com/example/restau/presentation/random/RandomScreen.kt
  app/src/main/java/com/example/restau/presentation/random/RandomViewModel.kt
  app/src/main/java/com/example/restau/presentation/reviewcreation/ReviewCreationScreen.kt
Labels: enhancement

#156 Feature/detail eventual connectivity #129
  app/src/main/java/com/example/restau/presentation/restaurant/RestaurantScreen.kt
  app/src/main/java/com/example/restau/presentation/restaurant/RestaurantViewModel.kt
Labels: enhancement

#160 Fix/no image on restaurant detail #158
  app/src/main/java/com/example/restau/presentation/restaurant/RestaurantScreen.kt
Labels: fix

#159 Fix done
  app/src/main/java/com/example/restau/data/repository/AuthRepositoryImpl.kt
Labels: fix

#162 Fix Random Screen
  app/src/main/java/com/example/restau/presentation/random/RandomViewModel.kt
Labels: bug

#164 Hidde search input no internet
  app/src/main/java/com/example/restau/presentation/search/SearchScreen.kt
Labels: fix

#166 Add BQ: How often does a user leave a review after using the "randomize restaurant" feature? implementation #165
  app/src/main/java/com/example/restau/data/repository/RandomReviewRepositoryImpl.kt
  app/src/main/java/com/example/restau/di/AppModule.kt
  app/src/main/java/com/example/restau/domain/repository/RandomReviewRepository.kt
  app/src/main/java/com/example/restau/domain/usecases/navPathsUseCases/CreatePath.kt
  app/src/main/java/com/example/restau/domain/usecases/navPathsUseCases/NavPathsUseCases.kt
  app/src/main/java/com/example/restau/domain/usecases/navPathsUseCases/UpdatePath.kt
  app/src/main/java/com/example/restau/domain/usecases/randomReviewUseCases/AddRandomReview.kt
  app/src/main/java/com/example/restau/domain/usecases/randomReviewUseCases/RandomReviewUseCases.kt
  app/src/main/java/com/example/restau/domain/usecases/randomReviewUseCases/UpdateRandomReview.kt
  app/src/main/java/com/example/restau/presentation/navigation/NavGraph.kt
  app/src/main/java/com/example/restau/presentation/random/RandomScreen.kt
  app/src/main/java/com/example/restau/presentation/random/RandomViewModel.kt
  app/src/main/java/com/example/restau/presentation/restaurant/RestaurantScreen.kt
  app/src/main/java/com/example/restau/presentation/reviewcreation/ReviewCreationEvent.kt
  app/src/main/java/com/example/restau/presentation/reviewcreation/ReviewCreationScreen.kt
  app/src/main/java/com/example/restau/presentation/reviewcreation/ReviewCreationViewModel.kt
  app/src/main/java/com/example/restau/presentation/reviewlist/ReviewListScreen.kt
Labels: enhancement

#175 Implementation of the Menu list
  app/src/main/java/com/example/restau/data/repository/MenuItemsRepositoryImpl.kt
  app/src/main/java/com/example/restau/di/AppModule.kt
  app/src/main/java/com/example/restau/domain/model/MenuItem.kt
  app/src/main/java/com/example/restau/domain/repository/MenuItemsRepository.kt
  app/src/main/java/com/example/restau/domain/usecases/menuItemsUseCases/GetRestaurantMenu.kt
  app/src/main/java/com/example/restau/domain/usecases/menuItemsUseCases/MenuItemsUseCases.kt
  app/src/main/java/com/example/restau/presentation/menuItems/MenuItemsEvent.kt
  app/src/main/java/com/example/restau/presentation/menuItems/MenuItemsScreen.kt
  app/src/main/java/com/example/restau/presentation/menuItems/MenuItemsState.kt
  app/src/main/java/com/example/restau/presentation/menuItems/MenuItemsViewModel.kt
  app/src/main/java/com/example/restau/presentation/menuItems/components/MenuItemCard.kt
  app/src/main/java/com/example/restau/presentation/navigation/NavGraph.kt
  app/src/main/java/com/example/restau/presentation/navigation/Route.kt
  app/src/main/java/com/example/restau/presentation/restaurant/RestaurantScreen.kt
Labels: enhancement

#177 Fixing performance issue from sprint 3
  app/src/main/java/com/example/restau/data/repository/RestaurantsRepositoryImpl.kt
  app/src/main/java/com/example/restau/data/repository/UsersRepositoryImpl.kt
  app/src/main/java/com/example/restau/presentation/navigator/NavigatorViewModel.kt
Labels: fix

#178 Implementing the recording of the map search time event
  app/src/main/java/com/example/restau/data/repository/MapSearchTimesRepositoryImpl.kt
  app/src/main/java/com/example/restau/di/AppModule.kt
  app/src/main/java/com/example/restau/domain/repository/MapSearchTimesRepository.kt
  app/src/main/java/com/example/restau/domain/usecases/analyticsUseCases/AnalyticsUseCases.kt
  app/src/main/java/com/example/restau/domain/usecases/analyticsUseCases/SendMapSearchTimes.kt
  app/src/main/java/com/example/restau/presentation/restaurant/RestaurantViewModel.kt
Labels: enhancement

#183 Feature/menu detail #173
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  app/src/main/java/com/example/restau/data/repository/MenuItemsRepositoryImpl.kt
  app/src/main/java/com/example/restau/domain/repository/MenuItemsRepository.kt
  app/src/main/java/com/example/restau/domain/usecases/menuItemsUseCases/GetMenuItem.kt
  app/src/main/java/com/example/restau/domain/usecases/menuItemsUseCases/MenuItemsUseCases.kt
  app/src/main/java/com/example/restau/presentation/menuDetail/MenuDetailEvent.kt
  app/src/main/java/com/example/restau/presentation/menuDetail/MenuDetailScreen.kt
  app/src/main/java/com/example/restau/presentation/menuDetail/MenuDetailState.kt
  app/src/main/java/com/example/restau/presentation/menuDetail/MenuDetailViewModel.kt
  app/src/main/java/com/example/restau/presentation/menuItems/MenuItemsScreen.kt
  app/src/main/java/com/example/restau/presentation/navigation/NavGraph.kt
  app/src/main/java/com/example/restau/presentation/navigation/Route.kt
Labels: enhancement

#180 Map micro optimization
  .idea/other.xml
  app/src/main/java/com/example/restau/presentation/map/MapScreen.kt
  app/src/main/java/com/example/restau/presentation/map/MapState.kt
  app/src/main/java/com/example/restau/presentation/map/MapViewModel.kt
Labels: enhancement
